ittagnelli/SARP

- src/components/Stabler/LeftBar.svelte
- src/routes/+layout.svelte
La pagina non viene visualizzata correttamente se cliccata dalla leftbar.
Questa pull request dovrebbe risolvere il problema.
Co-authored-by: Marco-Cellini <marco.cellini@istitutoagnelli.it>
> Fix layout problem

- .env
- .gitignore
- prisma/schema.prisma
> added prisma scheme and .env file

- src/app.html
- src/components/layout/footer.svelte
- src/components/layout/nav_bar.svelte
- src/components/layout/nav_item.svelte
- src/components/layout/nav_menu.svelte
- src/components/layout/nav_sub_item.svelte
- src/components/layout/nav_sub_menu.svelte
- src/components/layout/nav_sub_sub_item.svelte
- src/routes/+layout.svelte
- src/routes/+page.svelte
- refactor della navbar a componenti
> refactor della navbar a componenti

- src/routes/valutazioni/+page.server.js
- src/routes/valutazioni/+page.svelte
Ho risolto il problema con il modale sulla view valutazione, tutte le aziende non venivano restituite dalla API e quindi andava in errore
> Risolto problema con il modale

- src/routes/valutazioni/+page.svelte
Risolto il problema con la page valutazioni che ora funziona correttamente
> valutazioni: Rename import from store

- tests/fill_role.js
- tests/fill_user.js
Ho cambiato leggermente il fill_user.js per agevolare la creazione degli utenti e ho scritto fill_role.js per creare dei ruoli
> Aggiornati i tests per rispettare la wiki

- src/routes/utenti/+page.server.js
- src/routes/utenti/+page.svelte
Aggiunto il parametro can_login nella visualizzazione degli utenti.
> Aggiunto can_login

- tests/add_user_login.js
- tests/fill_DB.js
> Aggiunto script wiki

- src/lib/components/common/table.svelte
La funzione serve per determinare il numero degli utenti attivi e il loro rispettivo genere, modificando il testo di conseguenza
> Aggiunto show_users()

- .env
- .gitignore
- package-lock.json
- package.json
- src/hooks.server.js
- src/js/helper.js
- src/js/logger.js
- src/lib/components/common/table.svelte
- src/routes/+layout.svelte
- src/routes/aziende/+page.server.js
- src/routes/aziende/+page.svelte
- src/routes/faq/+page.server.js
- src/routes/faq/+page.svelte
- src/routes/logger/+server.js
- src/routes/login/+page.server.js
- src/routes/login/+page.svelte
- src/routes/logout/+page.server.js
- src/routes/presenze/+page.server.js
- src/routes/presenze/+page.svelte
- src/routes/stage/+page.server.js
- src/routes/stage/+page.svelte
- src/routes/utenti/+page.server.js
- src/routes/utenti/+page.svelte
- src/routes/valutazioni/+page.server.js
- src/routes/valutazioni/+page.svelte
- add client and server logging facilities
> Issue 63 logging

- .env
- .gitignore
- src/hooks.server.js
- src/js/audit.js
- src/js/prisma_db.js
- src/routes/+layout.svelte
- src/routes/aziende/+page.server.js
- src/routes/login/+page.server.js
- src/routes/logout/+page.server.js
- src/routes/presenze/+page.server.js
- src/routes/stage/+page.server.js
- src/routes/utenti/+page.server.js
- src/routes/valutazioni/+page.server.js
- aggiunto meccanismo di auditing implicito ed esplicito
- usato prisma middlewar
> Auditing issue#82

- src/routes/utenti/+page.svelte
PR per risolvere il controllo di validità del nome, cognome, telefono ed email.
> Issue 76 to 78

- src/routes/+layout.svelte
- src/routes/aziende/+page.svelte
- src/routes/presenze/+page.svelte
- src/routes/stage/+page.svelte
- src/routes/utenti/+page.svelte
Aggiunta validazione come richiesto
> fix issue-90

- prisma/schema.prisma
- src/js/helper.js
- src/lib/components/common/table.svelte
- src/lib/components/layout/footer.svelte
- src/lib/components/modal/input_area.svelte
- src/routes/+layout.svelte
- src/routes/aziende/+page.svelte
- src/routes/presenze/+page.svelte
- src/routes/stage/+page.svelte
- src/routes/ticket/+page.server.js
- src/routes/ticket/+page.svelte
- src/routes/utenti/+page.svelte
- src/routes/valutazioni/+page.svelte
- tests/imports.js
- aggiunta pagina segnalazioni per utenti NON developer
> - fix issue-48

- .env
- package-lock.json
- package.json
- src/lib/components/faq/faq.svelte
- src/routes/+layout.svelte
- src/routes/faq/+page.server.js
- src/routes/faq/+page.svelte
- static/faq/faq0_1.md
- static/faq/faq0_2.md
- static/faq/faq1_1.md
- static/faq/faq1_2.md
- svelte.config.js
- aggiornata la sezione FAQ
- aggiunta la possibilità di scrivere le FAQ in markdown
- aggiornato il wiki che spiega come usare le FAQ
> - fix issue-99 e issue-100

- src/js/helper.js
- src/routes/presenze/+page.svelte
Questa pull request introduce il controllo dell'orario e risolve un typo.
Risolve issue #114 e #115
> presenze: Fix typo e aggiunto controllo orario

- package-lock.json
- package.json
- server_static/changelog/changelog.md
- src/app.html
- src/routes/+layout.server.js
- src/routes/+layout.svelte
- src/service-worker.js
- static/manifest.json
- svelte.config.js
Questa pull request risolve le issue 132(introduce il service-worker) e issue 133(Fix google account)
> Issue 132 e Issue 133

- package.json
- server_static/changelog/changelog.md
- src/js/helper.js
- src/routes/login/+page.server.js
- src/routes/login/+page.svelte
- inibito login e quindi accesso a SARP se da mobile
- SARP è disponibile solo su PC
> - aggiunto riconoscimento piattaforma mobile

- src/routes/stage/+page.svelte
> Issue #137

- src/lib/components/common/table.svelte
Ho risolto il problema riguardante la issue-147 aggiungendo alle immagini, nel componente Table, un margine di 10px tutto intorno alla foto profilo dell'utente.
> issue-147: fix problem of picture-margin

- src/lib/components/common/table.svelte
> Issue 147 e 147

- src/js/helper.js
- src/routes/aziende/+page.server.js
- src/routes/login/+page.server.js
- src/routes/presenze/+page.server.js
- src/routes/stage/+page.server.js
- src/routes/ticket/+page.server.js
- src/routes/utenti/+page.server.js
- src/routes/valutazioni/+page.server.js
- refactor di catcherror per stampare correttamente le eccezioni di prisma
> Issue #155

- server_static/changelog/changelog.md
- src/routes/utenti/+page.svelte
- reso Utenti codiceF opzionale
- ridotto lunghezza minima nome e cognome a 3 caratteri
- reso natoA opzionale
> - fix issue 170

- src/js/helper.js
- src/lib/components/common/table.svelte
- src/routes/aziende/+page.svelte
- src/routes/stage/+page.svelte
- src/routes/utenti/+page.svelte
- aggiunto parametro size alla tabella per definire la dimesnione di un campo stringa
- modificata la page bar della tabella in modo da visualizzare sempre al massimo 20 pagine
> fix issue 172-173

- src/js/helper.js
- src/lib/components/common/table.svelte
- src/routes/sicurezza_sul_lavoro/corsi/+page.svelte
- src/routes/stage/+page.svelte
- possibilità di scaricare quanti attestati sicurezza si vuole
- limitato num immagini utente a 5
> Fix Issue189 190

- package-lock.json
- prisma/migrations/20230304171826_add_stage_contabilizzato/migration.sql
- prisma/schema.prisma
- src/routes/login/+page.server.js
- src/routes/login/+page.svelte
- src/routes/stage/+page.server.js
- src/routes/stage/+page.svelte
- fix bug in autenticazione dev per cypress
- modificato tabella pcto aggiunto flad contabilizzato
- modificato view stage per gestire flag contabilizzato
- ora è possibile contrassegnare uno stage come contabilizzato se tutte le sue ore sono state riportate in SIDI
> fix issue 197

- src/js/helper.js
- src/routes/presenze/+page.svelte
- src/routes/stage/+page.svelte
- aggiunto calcolo ore complessive PCTO per utente di tipo STUDENTE
- le ore complessive sono quelle approvate appartenenti a stage contabilizzati
> fix issue #199

- prisma/migrations/20230307154818_add_anno_scolastico_pcto/migration.sql
- prisma/schema.prisma
- src/routes/presenze/+page.svelte
- src/routes/stage/+page.server.js
- src/routes/stage/+page.svelte
- modificato DB aggiunto anno_scolastico a PCTO
- modificato front_end per supportare a.s.
- modificando back_end per supportare a.s.
- modificato presenze per visualizzare a.s. nel titolo dello stage in caso di stage con nome uguale
> fix issue#215

- src/routes/aziende/+page.server.js
Questa pull request risolve issue #205
> aziende: Ordina per id_convenzione

- prisma/migrations/20230309084143_add_data_test_sicurezza/migration.sql
- prisma/schema.prisma
- src/routes/sicurezza_sul_lavoro/corsi/+page.server.js
- src/routes/sicurezza_sul_lavoro/corsi/+page.svelte
- aggiornata tabella
- aggiornato modale insert e update
- aggiornato backend
> - aggiunto campo dataTest al corso di sicurezza

- src/routes/sicurezza_sul_lavoro/corsi/+page.svelte
- src/routes/stage/+page.svelte
> Fix select classi

- src/routes/sicurezza_sul_lavoro/corsi/+page.svelte
- src/routes/stage/+page.svelte
> Fix issue 231

- src/routes/stage/+page.server.js
Questa pull request risolve la issue #235
> Fix isse 235

- src/routes/presenze/+page.svelte
- refactor totale ore pcto visualizzate per uno studente
- vengono visualizzate le ore registrate, approvate e totali
> - fix#242: TOTALE ORE PCTO

- src/routes/verifica_stato/+page.svelte
- aggiunta linea in tabella con le ore totale di tutti i pcto di uno studente
> - fix#248: totale ore in verifica stato

- prisma/migrations/20230316001913_presenze_mobile/migration.sql
- prisma/schema.prisma
- src/lib/components/layout/nav_bar.svelte
- src/routes/+layout.svelte
- src/routes/+page.server.js
- src/routes/login/+page.server.js
- src/routes/login/+page.svelte
- src/routes/presenze/+page.server.js
- src/routes/presenze/+page.svelte
- src/routes/stage/+page.server.js
> Supporto presenza mobile

- src/routes/login/+page.server.js
- aggiunta generazione errore in caso di login fallito
> - fix#255: Login mancato messaggio errore

- prisma/migrations/20230423095130_add_pcto_durata_ore/migration.sql
- prisma/migrations/20230423103851_add_pcto_classe/migration.sql
- prisma/schema.prisma
- src/js/helper.js
- src/js/logger.js
- src/routes/pcto/stage/+page.server.js
- src/routes/pcto/stage/+page.svelte
- fix#265: Ore previste stage
- fix#267: stage per classe
- In fase di creazione dello stage è necessario specificare la classe e il numero di ore previste
> fix issue 265 e 267

- package.json
- server_static/changelog/changelog.md
- src/js/helper.js
- fix#273: logout 404
- risolto problema di reindirizzamento in fase di logout
> - fix#273: logout 404

- prisma/migrations/20230429155756_add_azienda_firma_convenzione/migration.sql
- prisma/schema.prisma
- src/routes/pcto/aziende/+page.server.js
- src/routes/pcto/aziende/+page.svelte
- aggiunto flag convenzione firmata modificabile solo da ADMIN
> - fix#276: PCTO Azienda flag firma

- prisma/migrations/20230430100908_add_pcto_firma_documenti/migration.sql
- prisma/schema.prisma
- src/routes/pcto/aziende/+page.svelte
- src/routes/pcto/stage/+page.server.js
- src/routes/pcto/stage/+page.svelte
- aggiunto flag documenti PCTO  firmati modificabile solo da ADMIN
> - fix#277: PCTO Stage flag firma feature

- server_static/rbac/acl.yml
- src/js/helper.js
- src/routes/pcto/presenze/+page.server.js
- src/routes/pcto/presenze/+page.svelte
- src/routes/pcto/stage/+page.svelte
- le ore sono automaticamente approvate e non è più possibile modificare da UI
- le presenze possono essere create solo da web da admin, tutor scolastico o tutor aziendale
- lo studente può solo consultare il suo monte ore e le ore scvolte via web e mobile
> - fix#278: PCTO presenze creaziono solo dei tutor

- prisma/migrations/20230519170220_add_pcto_valutazione_studente/migration.sql
- prisma/schema.prisma
- server_static/rbac/acl.yml
- src/js/helper.js
- src/routes/+layout.svelte
- src/routes/pcto/valutazione_studenti/+page.server.js
- src/routes/pcto/valutazione_studenti/+page.svelte
- src/routes/pcto/valutazione_studenti/qna_db.js
- il tutor aziendale può valutare gli studenti che hanno partecipato al PCTO di cui lui è tutor
- il tutor scoladtrico può visionare le valutazioni degli studenti per cui è tutor scolastico
- admin può eseguire tutte le operazioni
> - fix#309: aggiungere valutazione PCTO studente

- src/routes/pcto/valutazione_studenti/+page.svelte
- Lo stagista può solo visualizzare la sua valutazione, e non può ne modificarla ne aggiungerne una nuova
> - fix#329: Pulsante "Valuta Stagista" su /pcto/valutazione_studenti

- src/lib/components/common/table.svelte
- rimossa limitazione a 10 entry durante il filtro tabella
> - fix#330: filtro tabella limita risultato a 10

- src/lib/components/common/table.svelte
- src/routes/pcto/stage/+page.svelte
- Now user can set as many custom action as needed
> -fix#333: multiple custom action in table

- src/js/helper.js
- src/js/store.js
- src/lib/components/common/message_box.svelte
- Aggiunto componente MessageBox per visualizzare messaggi di tipo success, warning e danger
- Il messaggio ha un titolo ed un testo
- Il messaggio scompare automaticamente con un delay configurabile
> - fix#337: Alert Messages

- src/lib/components/common/tooltip.svelte
> - fix#338: Tooltip informativi

- src/routes/pcto/aziende/+page.svelte
- src/routes/pcto/presenze/+page.svelte
- src/routes/pcto/stage/+page.svelte
- src/routes/pcto/valutazione_studenti/+page.svelte
- src/routes/programmazione/classe/+page.svelte
- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
- src/routes/support/ticket/+page.svelte
- src/routes/support/utenti/+page.svelte
- aggiunti tooltip alla sezione programmazione annuale
- aggiunti tooltip a tutte le sezioni di SARP
> - fix#342: Tooltip per programmazione annuale

- src/lib/components/common/programmazione.svelte
- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
- campo titolo max 128 caratteri no enter
- campo sottoargomento max 512 caratteri no enter
> - fix#361: Campi più ampi in Programmazione Docente

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
- Il formato del libro è il seguente Cognome N.,Titolo,Casa Editrice, Anno Edizione (es: Boscaini M.,Imparare a programmare,Apogeo,2023)
> - fix#355:Formato Libro fisso in programmazione docente

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
- modificata regex per accettare anni tra 1000 e 29999
- modificata regex per accettare lettere maiuscole ovunque
> - fix#380: Validazione titolo libro errata

- src/lib/components/common/programmazione.svelte
Ora si può rimuovere un sotto argomento
> fix #376: Make remove_sotto_argomento works in latest changes

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
Questa PR rimuove la renderizzazione dei bullet list senza nessun argomento
> fix #379: Don't render empty sotto_sotto_argomenti

- src/lib/components/common/programmazione.svelte
- aggiunto colorazione icon
- update tooltip icone
> - fix#395: Distanziare icone più e cestino in programmazione docente

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
- support fino ad un max di 3 autori
- supporto a spazi in casa editrice e titolo
> - fix#397:Rilassare regex libro di testo in programmazione annuale

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
- aggiunto supporto a caratteri speciali ',(),[],/,&
> - fix#402: Apostrofo non permesso nel libro di testo in programmazione

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
> - fix#408:Formato Libro - rilassare regex al massimo

- package.json
- server_static/changelog/changelog.md
- src/routes/sicurezza_sul_lavoro/corsi/+page.server.js
- Ordine alfabetico crescente
- Lettere iniziale di nome e cognome maiuscole
> - fix#e410: Registro presenze sicurezza non in ordine alfabetico

- package.json
- server_static/changelog/changelog.md
- src/js/helper.js
- src/routes/programmazione/classe/+page.server.js
- src/routes/programmazione/docente/+page.server.js
- src/routes/sicurezza_sul_lavoro/corsi/+page.server.js
- aggiunto script per disabilitare utenti SARP
- rimossi studenti non più presenti nelle classi per a.s. 2023
> - `fix#`: Studenti in programmazione non ordinati enhancement

- src/routes/programmazione/template/+page.svelte
- src/routes/programmazione/template/+server.js
- il docente ora può condividere un template solo con docenti della stessa materia
> - fix#420: Condivione template impossibile in alcuni scenari

- package.json
- server_static/changelog/changelog.md
- src/js/helper.js
- src/routes/programmazione/classe/+page.server.js
- utils/scripts/exec_query.js
- Ordinate le materie nei documenti di programmazione in ordine alfabetico
> - `fix#434`: Documento programmazione classe senza programmi

- src/routes/support/utenti/+page.svelte
- utils/scripts/add_docenti_medie.sh
- fix#438: Caricamento docenti Medie a sistema tramite script automatico
> - fix#437: Aggiunta Istituto Medie

- prisma/migrations/20240206164553_add_pcto_presenza_as/migration.sql
- prisma/schema.prisma
- src/js/helper.js
- src/routes/pcto/presenze/+page.server.js
- src/routes/pcto/presenze/+page.svelte
- utils/scripts/exec_query.js
- aggiunto as in DB
- filtro presenze per as corrente
> - fix#PCTO Presenze visualizzazione relative a.s. in corso

- package.json
- server_static/changelog/changelog.md
- src/routes/pcto/aziende/+page.server.js
- src/routes/pcto/aziende/+page.svelte
- cambiato algoritmo di generazione dell'ID convenzione per un azienda
- rilassata regex per il telefono e indirizzo Azienda
> - `fix#488`:  PCTO small bugs

- prisma/migrations/20240331174830_add_utente_obiettivi_minimi/migration.sql
- prisma/schema.prisma
- src/routes/support/utenti/+page.server.js
- src/routes/support/utenti/+page.svelte
- Ora è possibile specificare per gli studenti se hanno diritto agli obiettivi minimi nel PDP o meno
> - fix#513: Studente Obiettivi Minimi

- prisma/migrations/20240404085405_add_pdp_obiettivi_minimi/migration.sql
- prisma/schema.prisma
- src/routes/pdp/docente/+page.server.js
- src/routes/pdp/docente/+page.svelte
- Docente può specificare un template di programmazione per gli studenti che hanno gli obiettivi minimi
> - fix#514: PDP Obiettivi Minimi

- prisma/migrations/20240409172731_add_pdp_sintesi_tempo_flag/migration.sql
- prisma/schema.prisma
- src/lib/components/common/table.svelte
- src/routes/pdp/docente/+page.server.js
- src/routes/pdp/docente/+page.svelte
- src/routes/pdp/genera_pdp/+page.server.js
- src/routes/pdp/genera_pdp/+page.svelte
- modifica alla tabella in modo da poter applicare filtri in AND
- aggiunti flag sintesi_vocale e tempo_esteso a PDP
- aggiunte colonne sintesi_vocale e tempo_esteso in PDP Alunni
- In tal modo la segreteria può verificare quali studenti di V hanno questi flag a true o meno
> - fix#525: PDP presenza voci specifiche

- package.json
- server_static/changelog/changelog.md
- src/routes/programmazione/classe/+page.server.js
- src/routes/programmazione/classe/+page.svelte
- src/routes/programmazione/docente/+page.server.js
- src/routes/programmazione/docente/+page.svelte
- Aggiornamento della sezione programmazione annuale in preparazione della fine del pentamestre
> `fix#538`: Fix vari per programmazione annuale

- src/routes/pdp/genera_pdp/+page.server.js
- risolto errore durante stampa PDP per studenti senza obiettivi minimi
> -fix#544: PDP errore stampa in mancanza di obiettivi minimi

- src/routes/pdp/template/dispensative.js
- aggiornato con nuova dizione: Integrazione dei libri di testo con materiale fornito dall'insegnante su supporto vario
> - fix#565: PDP-Dispensative D8

- src/routes/pcto/stage/+page.server.js
- Ora possono essere aggiunti ad un PCTO solo gli studenti che possono fare il login
> - fix#579: Possibile inserire studenti non più frequenanti ad uno stage

- src/routes/programmazione/docente/+page.svelte
- src/routes/programmazione/template/+page.svelte
-rimosso dal template iniziale il pulsante per rimuovere il libro
> -risolta issue-597
